/// ISO 3166-1 alpha-2 country codes with common English names, used for the
/// AI card-research sheet's country picker. Deliberately just a lookup
/// table (code, English name) — no locale-specific translation, since the
/// code itself (not the label) is what the backend and AI provider use.
class Country {
  const Country(this.code, this.name);

  final String code;
  final String name;
}

const List<Country> kCountries = [
  Country('EG', 'Egypt'),
  Country('SA', 'Saudi Arabia'),
  Country('AE', 'United Arab Emirates'),
  Country('QA', 'Qatar'),
  Country('KW', 'Kuwait'),
  Country('BH', 'Bahrain'),
  Country('OM', 'Oman'),
  Country('JO', 'Jordan'),
  Country('LB', 'Lebanon'),
  Country('IQ', 'Iraq'),
  Country('SY', 'Syria'),
  Country('YE', 'Yemen'),
  Country('PS', 'Palestine'),
  Country('LY', 'Libya'),
  Country('TN', 'Tunisia'),
  Country('DZ', 'Algeria'),
  Country('MA', 'Morocco'),
  Country('SD', 'Sudan'),
  Country('AF', 'Afghanistan'),
  Country('AL', 'Albania'),
  Country('AM', 'Armenia'),
  Country('AO', 'Angola'),
  Country('AR', 'Argentina'),
  Country('AT', 'Austria'),
  Country('AU', 'Australia'),
  Country('AZ', 'Azerbaijan'),
  Country('BA', 'Bosnia and Herzegovina'),
  Country('BD', 'Bangladesh'),
  Country('BE', 'Belgium'),
  Country('BG', 'Bulgaria'),
  Country('BN', 'Brunei'),
  Country('BO', 'Bolivia'),
  Country('BR', 'Brazil'),
  Country('BY', 'Belarus'),
  Country('CA', 'Canada'),
  Country('CH', 'Switzerland'),
  Country('CL', 'Chile'),
  Country('CM', 'Cameroon'),
  Country('CN', 'China'),
  Country('CO', 'Colombia'),
  Country('CR', 'Costa Rica'),
  Country('CY', 'Cyprus'),
  Country('CZ', 'Czechia'),
  Country('DE', 'Germany'),
  Country('DJ', 'Djibouti'),
  Country('DK', 'Denmark'),
  Country('DO', 'Dominican Republic'),
  Country('EC', 'Ecuador'),
  Country('EE', 'Estonia'),
  Country('ES', 'Spain'),
  Country('ET', 'Ethiopia'),
  Country('FI', 'Finland'),
  Country('FR', 'France'),
  Country('GB', 'United Kingdom'),
  Country('GE', 'Georgia'),
  Country('GH', 'Ghana'),
  Country('GR', 'Greece'),
  Country('GT', 'Guatemala'),
  Country('HK', 'Hong Kong'),
  Country('HR', 'Croatia'),
  Country('HU', 'Hungary'),
  Country('ID', 'Indonesia'),
  Country('IE', 'Ireland'),
  Country('IL', 'Israel'),
  Country('IN', 'India'),
  Country('IR', 'Iran'),
  Country('IS', 'Iceland'),
  Country('IT', 'Italy'),
  Country('JM', 'Jamaica'),
  Country('JP', 'Japan'),
  Country('KE', 'Kenya'),
  Country('KG', 'Kyrgyzstan'),
  Country('KH', 'Cambodia'),
  Country('KR', 'South Korea'),
  Country('KZ', 'Kazakhstan'),
  Country('LK', 'Sri Lanka'),
  Country('LT', 'Lithuania'),
  Country('LU', 'Luxembourg'),
  Country('LV', 'Latvia'),
  Country('MD', 'Moldova'),
  Country('ME', 'Montenegro'),
  Country('MG', 'Madagascar'),
  Country('MK', 'North Macedonia'),
  Country('ML', 'Mali'),
  Country('MM', 'Myanmar'),
  Country('MN', 'Mongolia'),
  Country('MR', 'Mauritania'),
  Country('MT', 'Malta'),
  Country('MU', 'Mauritius'),
  Country('MV', 'Maldives'),
  Country('MX', 'Mexico'),
  Country('MY', 'Malaysia'),
  Country('MZ', 'Mozambique'),
  Country('NA', 'Namibia'),
  Country('NE', 'Niger'),
  Country('NG', 'Nigeria'),
  Country('NL', 'Netherlands'),
  Country('NO', 'Norway'),
  Country('NP', 'Nepal'),
  Country('NZ', 'New Zealand'),
  Country('PA', 'Panama'),
  Country('PE', 'Peru'),
  Country('PH', 'Philippines'),
  Country('PK', 'Pakistan'),
  Country('PL', 'Poland'),
  Country('PT', 'Portugal'),
  Country('PY', 'Paraguay'),
  Country('RO', 'Romania'),
  Country('RS', 'Serbia'),
  Country('RU', 'Russia'),
  Country('RW', 'Rwanda'),
  Country('SE', 'Sweden'),
  Country('SG', 'Singapore'),
  Country('SI', 'Slovenia'),
  Country('SK', 'Slovakia'),
  Country('SN', 'Senegal'),
  Country('SO', 'Somalia'),
  Country('SV', 'El Salvador'),
  Country('TG', 'Togo'),
  Country('TH', 'Thailand'),
  Country('TJ', 'Tajikistan'),
  Country('TM', 'Turkmenistan'),
  Country('TR', 'Turkey'),
  Country('TT', 'Trinidad and Tobago'),
  Country('TW', 'Taiwan'),
  Country('TZ', 'Tanzania'),
  Country('UA', 'Ukraine'),
  Country('UG', 'Uganda'),
  Country('US', 'United States'),
  Country('UY', 'Uruguay'),
  Country('UZ', 'Uzbekistan'),
  Country('VE', 'Venezuela'),
  Country('VN', 'Vietnam'),
  Country('ZA', 'South Africa'),
  Country('ZM', 'Zambia'),
  Country('ZW', 'Zimbabwe'),
];

Country? countryByCode(String? code) {
  if (code == null) return null;
  final upper = code.toUpperCase();
  for (final country in kCountries) {
    if (country.code == upper) return country;
  }
  return null;
}
