import 'package:meta/meta.dart';
import 'package:work_tracker/core/date_time/plain_date.dart';
import 'package:work_tracker/core/domain/db_enums.dart';
import 'package:work_tracker/core/money/money.dart';
import 'package:work_tracker/features/finance/domain/financial_transaction.dart';

/// What a row of a facility's Related activity really is. The value is
/// computed once by `app_finance.facility_activity_items`, so the client
/// never re-derives it from account ids or transaction kinds.
enum FacilityActivityKind {
  ordinaryExpense('ordinary_expense'),
  installmentPurchase('installment_purchase'),
  installmentDownPayment('installment_down_payment'),
  facilityRepayment('facility_repayment'),
  repaymentReversal('repayment_reversal'),
  feeCharge('fee_charge'),
  purchaseInterest('purchase_interest'),
  installmentInterest('installment_interest'),
  other('other');

  const FacilityActivityKind(this.dbValue);
  final String dbValue;

  static FacilityActivityKind fromDb(String value) => values.firstWhere(
    (kind) => kind.dbValue == value,
    orElse: () => FacilityActivityKind.other,
  );
}

/// A row from `app_finance.facility_activity_items`.
@immutable
class FacilityActivityItem {
  const FacilityActivityItem({
    required this.transactionId,
    required this.accountId,
    required this.kind,
    required this.transactionKind,
    required this.occurredOn,
    required this.amountMinor,
    required this.currencyCode,
    required this.isSettled,
    this.planId,
    this.categoryId,
    this.title,
    this.notes,
    this.counterparty,
  });

  factory FacilityActivityItem.fromJson(Map<String, dynamic> json) =>
      FacilityActivityItem(
        transactionId: json['transaction_id'] as String,
        accountId: json['account_id'] as String,
        kind: FacilityActivityKind.fromDb(json['activity_kind'] as String),
        transactionKind: TransactionKind.fromDb(
          json['transaction_kind'] as String,
        ),
        occurredOn: PlainDate.parse(json['occurred_on'] as String),
        amountMinor: (json['amount_minor'] as num).toInt(),
        currencyCode: json['currency_code'] as String,
        isSettled: json['is_settled'] as bool? ?? false,
        planId: json['plan_id'] as String?,
        categoryId: json['category_id'] as String?,
        title: json['title'] as String?,
        notes: json['notes'] as String?,
        counterparty: json['counterparty'] as String?,
      );

  final String transactionId;
  final String accountId;
  final FacilityActivityKind kind;
  final TransactionKind transactionKind;
  final PlainDate occurredOn;
  final int amountMinor;
  final String currencyCode;

  /// The charge already sits in a statement cycle that has been paid into.
  final bool isSettled;

  final String? planId;
  final String? categoryId;
  final String? title;
  final String? notes;
  final String? counterparty;

  Money get amount => Money(minor: amountMinor, currencyCode: currencyCode);

  /// The ledger row behind this activity, in the shape the canonical
  /// transaction editor expects. An expense charged to a facility keeps the
  /// facility as its source account, exactly as stored.
  FinancialTransaction toTransaction() => FinancialTransaction(
    id: transactionId,
    kind: transactionKind,
    occurredOn: occurredOn,
    amountMinor: amountMinor,
    currencyCode: currencyCode,
    sourceAccountId: transactionKind == TransactionKind.transfer
        ? null
        : accountId,
    destinationAccountId: null,
    categoryId: categoryId,
    counterparty: counterparty,
    title: title,
    notes: notes,
  );
}

/// The single capability decision for a Related activity row: which editor,
/// if any, may open it. Widgets read this instead of testing kinds and
/// account ids themselves, so no row can ever offer a dead Edit action.
enum FacilityActivityAction {
  /// Ordinary expense: the canonical Edit transaction screen.
  editTransaction,

  /// Financed purchase or its down payment: the installment-plan editor.
  editPlan,

  /// Facility repayment: the existing payment reversal flow.
  reversePayment,

  /// Already inside a paid statement; corrections go through a reversal.
  explainSettled,

  /// Generated by a fee rule; the rule is the thing to change.
  explainFee,

  /// Immutable system record such as a payment reversal.
  explainSystem,
}

FacilityActivityAction resolveFacilityActivityAction(
  FacilityActivityItem item,
) => switch (item.kind) {
  FacilityActivityKind.ordinaryExpense =>
    item.isSettled
        ? FacilityActivityAction.explainSettled
        : FacilityActivityAction.editTransaction,
  FacilityActivityKind.installmentPurchase ||
  FacilityActivityKind.installmentDownPayment =>
    FacilityActivityAction.editPlan,
  FacilityActivityKind.facilityRepayment =>
    FacilityActivityAction.reversePayment,
  FacilityActivityKind.feeCharge ||
  FacilityActivityKind.purchaseInterest ||
  FacilityActivityKind.installmentInterest => FacilityActivityAction.explainFee,
  FacilityActivityKind.repaymentReversal ||
  FacilityActivityKind.other => FacilityActivityAction.explainSystem,
};
